import React from 'react';
import { PageHeader, Button } from 'antd';
import { LogoutOutlined } from '@ant-design/icons';
import Router from 'next/router';
import Head from 'next/head';
import { getAuth, signOut } from 'firebase/auth';

import { ROUTES } from '../constants';

import styles from '../../styles/Layout.module.less';

const onLogout = () => {
  const auth = getAuth();
  signOut(auth)
    .then((res) => {
      console.log('Log out successfuly: ', res);
      Router.push(ROUTES.login);
    })
    .catch((error) => {
      console.log('Error while log out: ', error);
    });
};

const onBack = () => Router.back();

export default function getLayout({ title, subTitle = '' }) {
  return function getWrappedPage(page, appContext) {
    return (
      <React.Fragment>
        <Head>
          <title>Money tracker</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <PageHeader
          className={styles.sitePageHeader}
          onBack={onBack}
          title={title}
          subTitle={subTitle || appContext?.user?.displayName}
          ghost={false}
          extra={[
            <Button
              key='1'
              type='primary'
              onClick={onLogout}
              icon={<LogoutOutlined />}
              size='large'
            >
              Log out
            </Button>,
          ]}
        />

        <main>{page}</main>
      </React.Fragment>
    );
  };
}
