import React from 'react';
import Head from 'next/head';

import { useAuth } from '../hooks/useAuth';

import { Spin } from '../components/Spin';
import getLayout from '../utils/getLayout';

const DELAY = 500;

export default function Home() {
  const isLoading = useAuth({ delay: DELAY });

  return (
    <React.Fragment>
      <Head>
        <title>Money tracker</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {isLoading && <Spin isFullScreen={true} size='large' />}
    </React.Fragment>
  );
}

Home.getLayout = getLayout({ title: 'Home' });
