import React from 'react';
import Head from 'next/head';

import styles from '../styles/Home.module.less';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Money tracker</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Home page</h1>
      </main>
    </div>
  );
}
